# ROM splitter configuration file
name: "N64 PIF IPL NTSC"

# checksums from ROM header offsets 0x10 and 0x14
# used for auto configuration detection
checksum1: 0x40898000
checksum2: 0x3C08A404

# base filename used for outputs (please, no spaces)
basename: "pif.ntsc"

# memory map from KSEG0 RAM addresses to ROM offsets
memory:
   # start     end         ram-to-rom
   - [0x1FC00000, 0x1FC000D3, 0x1FC00000]
   - [0xA4000000, 0xA40007FF, 0xA3FFFF2C]  # 00D4-07FF

# ranges to split the ROM into
# types:
#   asm      - MIPS assembly block.  Symbol names are in 'labels' list below
ranges:
   # start,  end,      type,     label
   - [0x000000, 0x0000D4, "asm"]
   - [0x0000D4, 0x000800, "asm"]

# Labels for functions or data memory addresses
# All label addresses are RAM addresses
# Order does not matter
labels:
   - [0x1FC00000, "Reset"]
   - [0xA4000000, "Main", 0xA400013C]
   - [0xA4000550, "Multiply"]
   - [0xA4000184, "proc_A4000184", 0xA4000550]

